"""create categories and expenses

Revision ID: 8ca2d773dfb1
Revises: 47a811e91c15
Create Date: 2026-08-31 18:40:35.709045

"""

import uuid

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8ca2d773dfb1"
down_revision = "47a811e91c15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("normalized_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint(
            "user_id", "normalized_name", name="uq_categories_user_normalized_name"
        ),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index("ix_categories_user_id", ["user_id"], unique=False)

    categories_table = sa.table(
        "categories",
        sa.column("public_id", sa.Uuid()),
        sa.column("user_id", sa.Integer()),
        sa.column("name", sa.String()),
        sa.column("normalized_name", sa.String()),
    )
    system_categories = (
        ("10000000-0000-0000-0000-000000000001", "Продукты"),
        ("10000000-0000-0000-0000-000000000002", "Транспорт"),
        ("10000000-0000-0000-0000-000000000003", "Жильё"),
        ("10000000-0000-0000-0000-000000000004", "Здоровье"),
        ("10000000-0000-0000-0000-000000000005", "Развлечения"),
        ("10000000-0000-0000-0000-000000000006", "Покупки"),
        ("10000000-0000-0000-0000-000000000007", "Образование"),
        ("10000000-0000-0000-0000-000000000008", "Другое"),
    )
    op.bulk_insert(
        categories_table,
        [
            {
                "public_id": uuid.UUID(public_id),
                "user_id": None,
                "name": name,
                "normalized_name": name.casefold(),
            }
            for public_id, name in system_categories
        ],
    )

    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("merchant", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("client_operation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount > 0", name="ck_expenses_amount_positive"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint(
            "user_id", "client_operation_id", name="uq_expenses_user_client_operation"
        ),
    )
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.create_index("ix_expenses_user_category", ["user_id", "category_id"], unique=False)
        batch_op.create_index(
            "ix_expenses_user_expense_date", ["user_id", "expense_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_index("ix_expenses_user_expense_date")
        batch_op.drop_index("ix_expenses_user_category")

    op.drop_table("expenses")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index("ix_categories_user_id")

    op.drop_table("categories")
    # ### end Alembic commands ###
