complexity:
  LongMethod:
    active: true
    allowedLines: 140
  LongParameterList:
    active: true
    allowedFunctionParameters: 10
    allowedConstructorParameters: 12
    ignoreDefaultParameters: true
  TooManyFunctions:
    active: true
    allowedFunctionsPerFile: 20
    allowedFunctionsPerClass: 20

naming:
  ConstructorParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9_]*'
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: true
    max: 5
  WildcardImport:
    active: false
